# Generated by Django 3.1 on 2020-08-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_historicalcategory'),
        ('manufacturer', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='category.Category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufacturer.manufacturer'),
        ),
    ]
